spring:
  kafka:
    consumer:
      auto-offset-reset: earliest
      group-id: testgroup

kafka:
  bootstrap-servers: localhost:9092
  topic:
    c3topic: c3testtopic
    spring-integration-kafka: spring-integration-kafka.t